version: "3"
services:
  chz-transaction-monitor:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "8000"
    ports:
      - 3003:8000
    container_name: chz-transaction-monitor
    volumes:
      - .:/usr/src/app
    environment:
      TERM: xterm-256color
    env_file:
      - .env

  chz-transaction-monitor-mongodb:
    image: mongo:5.0
    restart: always
    ports: 
      - 27017:27017
    container_name: chz-transaction-monitor-mongodb
    environment:
      TERM: xterm-256color
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
